/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : string,
  'buyerEmail' : string,
  'paymentMethod' : PaymentMethod,
  'productId' : bigint,
  'buyerUsername' : string,
  'buyerContact' : string,
  'buyer' : Principal,
}
export type PaymentMethod = { 'cryptocurrency' : null } |
  { 'payIn3Installments' : null } |
  { 'ukGiftCard' : null } |
  { 'paypal' : null };
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'description' : string,
  'available' : boolean,
  'gameName' : string,
  'price' : bigint,
  'accountDetails' : string,
}
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export type Result = { 'ok' : null } |
  { 'err' : string };
export interface UserProfile {
  'contact' : string,
  'username' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminUser' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, string], Result>,
  'addOrder' : ActorMethod<[bigint, PaymentMethod, string], bigint>,
  'addProduct' : ActorMethod<
    [string, bigint, string, string, string, bigint, boolean],
    Result
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUsername' : ActorMethod<[string], undefined>,
  'deleteCategory' : ActorMethod<[bigint], Result>,
  'deleteProduct' : ActorMethod<[bigint], Result>,
  'getAllCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getAvailableProductsByPrice' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryById' : ActorMethod<[bigint], ProductCategory>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getOrdersByUsername' : ActorMethod<[string], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'hasUsername' : ActorMethod<[Principal], boolean>,
  'isAdminUsername' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'removeAdminUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateCategory' : ActorMethod<[bigint, string, string], Result>,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, string, string, bigint, boolean],
    Result
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];