/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductCategory = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const PaymentMethod = IDL.Variant({
  'cryptocurrency' : IDL.Null,
  'payIn3Installments' : IDL.Null,
  'ukGiftCard' : IDL.Null,
  'paypal' : IDL.Null,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
});
export const Order = IDL.Record({
  'status' : IDL.Text,
  'buyerEmail' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'giftCardBalance' : IDL.Text,
  'giftCardNumber' : IDL.Text,
  'productId' : IDL.Nat,
  'buyerUsername' : IDL.Text,
  'approvalStatus' : ApprovalStatus,
  'buyerContact' : IDL.Text,
  'buyer' : IDL.Principal,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'categoryId' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'gameName' : IDL.Text,
  'price' : IDL.Nat,
  'accountDetails' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'contact' : IDL.Text,
  'username' : IDL.Text,
  'email' : IDL.Text,
});
export const StoreSettings = IDL.Record({
  'bitcoinWalletAddress' : IDL.Text,
  'paypalWalletAddress' : IDL.Text,
  'ethereumWalletAddress' : IDL.Text,
});
export const SubscriptionTier = IDL.Record({
  'id' : IDL.Nat,
  'freeTrialEnabled' : IDL.Bool,
  'name' : IDL.Text,
  'yearlyPrice' : IDL.Float64,
  'monthlyPrice' : IDL.Float64,
  'perks' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAdminUser' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
  'addProduct' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
      [Result],
      [],
    ),
  'approveOrder' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUsername' : IDL.Func([IDL.Text], [], []),
  'declineOrder' : IDL.Func(
      [IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'deleteCategory' : IDL.Func([IDL.Nat], [Result], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [Result], []),
  'getAdminPinLockoutStatus' : IDL.Func(
      [IDL.Principal],
      [IDL.Record({ 'remainingSeconds' : IDL.Int, 'isLockedOut' : IDL.Bool })],
      [],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAvailableProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategoryById' : IDL.Func([IDL.Nat], [ProductCategory], ['query']),
  'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
  'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrdersByBuyer' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
  'getSubscriptionTiers' : IDL.Func([], [IDL.Vec(SubscriptionTier)], ['query']),
  'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUsernameByPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(IDL.Text)],
      ['query'],
    ),
  'hasUsername' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'isAdminUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func(
      [
        IDL.Principal,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        PaymentMethod,
        IDL.Text,
        IDL.Text,
      ],
      [Result],
      [],
    ),
  'removeAdminUser' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSubscriptionTierFreeTrial' : IDL.Func([IDL.Nat, IDL.Bool], [Result], []),
  'updateBitcoinWalletAddress' : IDL.Func([IDL.Text], [Result], []),
  'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
  'updateEthereumWalletAddress' : IDL.Func([IDL.Text], [Result], []),
  'updatePaypalWalletAddress' : IDL.Func([IDL.Text], [Result], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
      ],
      [Result],
      [],
    ),
  'updateSubscriptionTierPrices' : IDL.Func(
      [IDL.Nat, IDL.Float64, IDL.Float64],
      [Result],
      [],
    ),
  'verifyAdminPin' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Result = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductCategory = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const PaymentMethod = IDL.Variant({
    'cryptocurrency' : IDL.Null,
    'payIn3Installments' : IDL.Null,
    'ukGiftCard' : IDL.Null,
    'paypal' : IDL.Null,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
  });
  const Order = IDL.Record({
    'status' : IDL.Text,
    'buyerEmail' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'giftCardBalance' : IDL.Text,
    'giftCardNumber' : IDL.Text,
    'productId' : IDL.Nat,
    'buyerUsername' : IDL.Text,
    'approvalStatus' : ApprovalStatus,
    'buyerContact' : IDL.Text,
    'buyer' : IDL.Principal,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'categoryId' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'gameName' : IDL.Text,
    'price' : IDL.Nat,
    'accountDetails' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'contact' : IDL.Text,
    'username' : IDL.Text,
    'email' : IDL.Text,
  });
  const StoreSettings = IDL.Record({
    'bitcoinWalletAddress' : IDL.Text,
    'paypalWalletAddress' : IDL.Text,
    'ethereumWalletAddress' : IDL.Text,
  });
  const SubscriptionTier = IDL.Record({
    'id' : IDL.Nat,
    'freeTrialEnabled' : IDL.Bool,
    'name' : IDL.Text,
    'yearlyPrice' : IDL.Float64,
    'monthlyPrice' : IDL.Float64,
    'perks' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAdminUser' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Text], [Result], []),
    'addProduct' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Bool],
        [Result],
        [],
      ),
    'approveOrder' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUsername' : IDL.Func([IDL.Text], [], []),
    'declineOrder' : IDL.Func(
        [IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'deleteCategory' : IDL.Func([IDL.Nat], [Result], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [Result], []),
    'getAdminPinLockoutStatus' : IDL.Func(
        [IDL.Principal],
        [
          IDL.Record({
            'remainingSeconds' : IDL.Int,
            'isLockedOut' : IDL.Bool,
          }),
        ],
        [],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(ProductCategory)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAvailableProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAvailableProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategoryById' : IDL.Func([IDL.Nat], [ProductCategory], ['query']),
    'getOrderById' : IDL.Func([IDL.Nat], [Order], ['query']),
    'getOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrdersByBuyer' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getProductById' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getStoreSettings' : IDL.Func([], [StoreSettings], ['query']),
    'getSubscriptionTiers' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionTier)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([IDL.Principal], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUsernameByPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(IDL.Text)],
        ['query'],
      ),
    'hasUsername' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'isAdminUsername' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func(
        [
          IDL.Principal,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          PaymentMethod,
          IDL.Text,
          IDL.Text,
        ],
        [Result],
        [],
      ),
    'removeAdminUser' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSubscriptionTierFreeTrial' : IDL.Func(
        [IDL.Nat, IDL.Bool],
        [Result],
        [],
      ),
    'updateBitcoinWalletAddress' : IDL.Func([IDL.Text], [Result], []),
    'updateCategory' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [Result], []),
    'updateEthereumWalletAddress' : IDL.Func([IDL.Text], [Result], []),
    'updatePaypalWalletAddress' : IDL.Func([IDL.Text], [Result], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
        ],
        [Result],
        [],
      ),
    'updateSubscriptionTierPrices' : IDL.Func(
        [IDL.Nat, IDL.Float64, IDL.Float64],
        [Result],
        [],
      ),
    'verifyAdminPin' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Bool, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };