/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'status' : string,
  'buyerEmail' : string,
  'paymentMethod' : PaymentMethod,
  'giftCardBalance' : string,
  'giftCardNumber' : string,
  'productId' : bigint,
  'buyerUsername' : string,
  'approvalStatus' : OrderApprovalStatus,
  'buyerContact' : string,
  'buyer' : Principal,
}
export type OrderApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'declined' : null };
export type PaymentMethod = { 'cryptocurrency' : null } |
  { 'payIn3Installments' : null } |
  { 'ukGiftCard' : null } |
  { 'paypal' : null };
export interface Product {
  'id' : bigint,
  'categoryId' : bigint,
  'title' : string,
  'description' : string,
  'available' : boolean,
  'gameName' : string,
  'price' : bigint,
  'accountDetails' : string,
}
export interface ProductCategory {
  'id' : bigint,
  'name' : string,
  'description' : string,
}
export interface StoreSettings {
  'bitcoinWalletAddress' : string,
  'paypalWalletAddress' : string,
  'ethereumWalletAddress' : string,
}
export interface SubscriptionTier {
  'id' : bigint,
  'freeTrialEnabled' : boolean,
  'name' : string,
  'yearlyPrice' : number,
  'monthlyPrice' : number,
  'perks' : Array<string>,
}
export interface UserProfile {
  'contact' : string,
  'username' : string,
  'email' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addAdminUser' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'addProduct' : ActorMethod<
    [string, bigint, string, string, string, bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'approveOrder' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubscriptionTier' : ActorMethod<
    [string, number, number, Array<string>, boolean],
    { 'ok' : SubscriptionTier } |
      { 'err' : string }
  >,
  'createUsername' : ActorMethod<[string], undefined>,
  'declineOrder' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteCategory' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'deleteProduct' : ActorMethod<[bigint], { 'ok' : null } | { 'err' : string }>,
  'deleteSubscriptionTier' : ActorMethod<
    [bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getAllCategories' : ActorMethod<[], Array<ProductCategory>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAvailableProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategoryById' : ActorMethod<[bigint], ProductCategory>,
  'getOrderById' : ActorMethod<[bigint], Order>,
  'getOrders' : ActorMethod<[], Array<Order>>,
  'getOrdersByBuyer' : ActorMethod<[Principal], Array<Order>>,
  'getProductById' : ActorMethod<[bigint], Product>,
  'getStoreSettings' : ActorMethod<[], StoreSettings>,
  'getSubscriptionTiers' : ActorMethod<[], Array<SubscriptionTier>>,
  'getUserOrders' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getUsernameByPrincipal' : ActorMethod<[Principal], [] | [string]>,
  'hasUsername' : ActorMethod<[Principal], boolean>,
  'isAdminUsername' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isUsernameAvailable' : ActorMethod<[string], boolean>,
  'placeOrder' : ActorMethod<
    [Principal, string, string, string, bigint, PaymentMethod, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'removeAdminUser' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setSubscriptionTierFreeTrial' : ActorMethod<
    [bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateBitcoinWalletAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateCategory' : ActorMethod<
    [bigint, string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateEthereumWalletAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updatePaypalWalletAddress' : ActorMethod<
    [string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [bigint, string, bigint, string, string, string, bigint, boolean],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'updateSubscriptionTierPrices' : ActorMethod<
    [bigint, number, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];